using ViewModelSubject;
using ViewModelSubjectDemo;
using ViewModelSubjectDemo.ViewModel;

IViewModelSubject subject = new ViewModelSubject.ViewModelSubject();
SubjectViewModel subjectViewModel = new (subject);
ObserverViewModel observerViewModel1 = new (subject, 1);
ObserverViewModel observerViewModel2 = new (subject, 2);
subjectViewModel.Send(true);
subjectViewModel.Send(false);
subjectViewModel.Send(true);
subjectViewModel.Send(false);
Console.WriteLine("-----------------");
subjectViewModel.Send(1);
subjectViewModel.Send(2);
subjectViewModel.Send(3);
subjectViewModel.Send(4);
Console.WriteLine("-----------------");
subjectViewModel.Send();
Console.ReadLine();
observerViewModel1.Dispose();
observerViewModel2.Dispose();
